project:
  type: website
  output-dir: docs

website:
  title: "UAlg Science Community"
  favicon: pics/favicon_bw.png
  navbar:
    search: true
    tools:
      - icon: house-heart-fill
        menu:
          - text: UAlg
            url: https://www.ualg.pt/
    left:
      - href: index.qmd
        text: "Home"
      - href: posts.qmd
        text: "News"
      - href: about.qmd
        text: "About"
      - href: calendar.qmd
        text: "Calendar"
      - text: "Documents"
        menu:
          - documents/fct_tenure.qmd
          - documents/crup.qmd
          - documents/stellar.qmd
      - href: extra.qmd
        text: "Extra"
      
  back-to-top-navigation: true
  page-footer: 
    left: "Copyright 2023, UAlg Science Community" 
    right: 
      - icon: github
        href: https://github.com/UALGResearchers
    background: light

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: source

